# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon May  9 21:15:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 452)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSelectRootFolder = QtGui.QPushButton(self.centralWidget)
        self.btnSelectRootFolder.setObjectName("btnSelectRootFolder")
        self.verticalLayout.addWidget(self.btnSelectRootFolder)
        self.btnSelectFolder1 = QtGui.QPushButton(self.centralWidget)
        self.btnSelectFolder1.setObjectName("btnSelectFolder1")
        self.verticalLayout.addWidget(self.btnSelectFolder1)
        self.btnSelectFolder2 = QtGui.QPushButton(self.centralWidget)
        self.btnSelectFolder2.setObjectName("btnSelectFolder2")
        self.verticalLayout.addWidget(self.btnSelectFolder2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblRootFolder = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRootFolder.sizePolicy().hasHeightForWidth())
        self.lblRootFolder.setSizePolicy(sizePolicy)
        self.lblRootFolder.setText("")
        self.lblRootFolder.setObjectName("lblRootFolder")
        self.verticalLayout_3.addWidget(self.lblRootFolder)
        self.lblFolder1 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolder1.sizePolicy().hasHeightForWidth())
        self.lblFolder1.setSizePolicy(sizePolicy)
        self.lblFolder1.setText("")
        self.lblFolder1.setObjectName("lblFolder1")
        self.verticalLayout_3.addWidget(self.lblFolder1)
        self.lblFolder2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolder2.sizePolicy().hasHeightForWidth())
        self.lblFolder2.setSizePolicy(sizePolicy)
        self.lblFolder2.setText("")
        self.lblFolder2.setObjectName("lblFolder2")
        self.verticalLayout_3.addWidget(self.lblFolder2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lvImages = QtGui.QListWidget(self.centralWidget)
        self.lvImages.setEnabled(False)
        self.lvImages.setObjectName("lvImages")
        self.verticalLayout_2.addWidget(self.lvImages)
        self.btnMoveToFolder1 = QtGui.QPushButton(self.centralWidget)
        self.btnMoveToFolder1.setObjectName("btnMoveToFolder1")
        self.verticalLayout_2.addWidget(self.btnMoveToFolder1)
        self.btnMoveToFolder2 = QtGui.QPushButton(self.centralWidget)
        self.btnMoveToFolder2.setObjectName("btnMoveToFolder2")
        self.verticalLayout_2.addWidget(self.btnMoveToFolder2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.lblImagePreview = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImagePreview.sizePolicy().hasHeightForWidth())
        self.lblImagePreview.setSizePolicy(sizePolicy)
        self.lblImagePreview.setAutoFillBackground(False)
        self.lblImagePreview.setText("")
        self.lblImagePreview.setScaledContents(True)
        self.lblImagePreview.setObjectName("lblImagePreview")
        self.horizontalLayout_2.addWidget(self.lblImagePreview)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyImageSelector", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectRootFolder.setText(QtGui.QApplication.translate("MainWindow", "Select images folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFolder1.setText(QtGui.QApplication.translate("MainWindow", "Select folder 1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFolder2.setText(QtGui.QApplication.translate("MainWindow", "Select folder 2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveToFolder1.setText(QtGui.QApplication.translate("MainWindow", "Send to folder 1 (or press 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveToFolder2.setText(QtGui.QApplication.translate("MainWindow", "Send to folder 2 (or press 2)", None, QtGui.QApplication.UnicodeUTF8))

